[[libssh]]
arch = "aarch64"
git-tree-sha1 = "e0cd5a77b916daf77dd8a8224a4fb391796d1a6b"
os = "macos"

    [[libssh.download]]
    sha256 = "bc10f4ce83ee998f66fb0b927c3cff37e72e2495b2947b93018f99b70152574b"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.aarch64-apple-darwin.tar.gz"
[[libssh]]
arch = "aarch64"
git-tree-sha1 = "ffc0a06e387ef1f7c610c4e98d820abc1a80d1a8"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "d99c3a62f739d80a8e2eb0f21e0e39104a5827fb409cb5d454bc81d67585b145"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.aarch64-linux-gnu.tar.gz"
[[libssh]]
arch = "aarch64"
git-tree-sha1 = "78eacb57131e90dad1efbdbaa620eee1170188db"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "27314e09e6d288fe29b4b267ef5150b9f37f1e4d1b88b4bad43b72c19e6a3f3b"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.aarch64-linux-musl.tar.gz"
[[libssh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c5b09c2fdf3b6a46ecd4d829ecc28b36e468255e"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "2c2ecf6437de197023957292943456c6fe028a4ae7fb5d6a75652fb32c01e2ad"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.armv6l-linux-gnueabihf.tar.gz"
[[libssh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ed94a7536068e578b8f31d37ae476bfc11c1f2f"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "7c81bff7757e6cc04375d9d73d0f60006660813b94895dfee4c3b24e09e74804"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.armv6l-linux-musleabihf.tar.gz"
[[libssh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9d728e012a7eac60d8befd65f51b5c0932567716"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "f6d36305f6d8c6b270e1c64697704c81c65936ee73141b6c740fc7e89dda1ed4"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.armv7l-linux-gnueabihf.tar.gz"
[[libssh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "185e994b3645434aed122ed404d2eba97d5c41ce"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "d21859c1214d229dc74e40eedde21cfbcc2e629914b70d9669b52605dda347c3"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.armv7l-linux-musleabihf.tar.gz"
[[libssh]]
arch = "i686"
git-tree-sha1 = "e69db27bdbe919fd5c64f2fd71192c6307266f00"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "ecd752ca7771b1f0c22ecfe573bbeb9952305bd577140ceab3cb2f8d4bfb65d4"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.i686-linux-gnu.tar.gz"
[[libssh]]
arch = "i686"
git-tree-sha1 = "c50be29b9c2438e22d7257353682683ac9a57d71"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "ea98280d61cd9991837eee6d231a2dd7fa980f0726268c77a86678850393103d"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.i686-linux-musl.tar.gz"
[[libssh]]
arch = "i686"
git-tree-sha1 = "1fb350e929453fbf7437c1c99a113d67904f382c"
os = "windows"

    [[libssh.download]]
    sha256 = "cc82ab8242a659e13cf86835ddedafab0d65f31b82655f2f5185e3c7a838d43e"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.i686-w64-mingw32.tar.gz"
[[libssh]]
arch = "powerpc64le"
git-tree-sha1 = "2648d3ad0bb9545f212bad645ce3707330462076"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "29eb5466b5bca53ce22f4ee52cfe7fee863b53d9ea53ebcc3ace5b4b4f3c3f12"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.powerpc64le-linux-gnu.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "305946707b42f3d443cea5b6ac227b8896378586"
os = "macos"

    [[libssh.download]]
    sha256 = "35b2dd3be0b669c668e54af1a49a79db7766917d14197d60cb21c550e6ad0d04"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.x86_64-apple-darwin.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "bf6b2e8a8f015981a4350cac96bfb2ef9f96aabf"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "d910312dd51a6a5fa433b03d8cfe13e19fded6371d2ff5fd003332b202bd0a58"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.x86_64-linux-gnu.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "9f0c03b8122a869930ac69ac72b4f96aae715206"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "11233067437c25d50fdb47e79702b7147b4ab98bbf955eb3c3d1dc822ea889bf"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.x86_64-linux-musl.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "0c0071ad1885e5f22bfb4dac28362195a4119375"
os = "freebsd"

    [[libssh.download]]
    sha256 = "ffc77acb9377548387eee5315d05fabb9c246defb532db6d5af7d74c27822975"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.x86_64-unknown-freebsd.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "09861c408c81e67a9277aeded2af0fe1128a8fe9"
os = "windows"

    [[libssh.download]]
    sha256 = "fb64a9332914cf92beefab7728a0b1d2780c47abfafc562fe6c9a7e8f32ac781"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.1+0/libssh.v0.11.1.x86_64-w64-mingw32.tar.gz"
