[[libssh]]
arch = "aarch64"
git-tree-sha1 = "0317adef9c7d9582ada41f86ec388fb99ec4da2a"
os = "macos"

    [[libssh.download]]
    sha256 = "9cadbd7f223bcc89b4aaa5047da878d6f5bbe5d0bd53afc566081615f7fbc2ae"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.aarch64-apple-darwin.tar.gz"
[[libssh]]
arch = "aarch64"
git-tree-sha1 = "ebf4c3e68568e5a52bd89e07aec21b2c75a9a190"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "d50be5d0acf0080e976d1203a4c7bd0a86fbad6694b4d16eb83b132f511e2132"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.aarch64-linux-gnu.tar.gz"
[[libssh]]
arch = "aarch64"
git-tree-sha1 = "4b9b917e8994834a07bc8381f59df2f43b501084"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "a64b864d1625d25c9069cd0938d90e6bba6644a8771441a7f4602920a8c897b6"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.aarch64-linux-musl.tar.gz"
[[libssh]]
arch = "aarch64"
git-tree-sha1 = "c0d7afd9d86d0a19ede9b8bdc2706afda1d6cbbe"
os = "freebsd"

    [[libssh.download]]
    sha256 = "e2cb979a8b9d53eff2a40924842d8a7a5e9e2468da253f9c02c276a4b7b5b84d"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.aarch64-unknown-freebsd.tar.gz"
[[libssh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4db627ff3dfae20638908129a2e0253a0bfed7c2"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "14693c1f5207583dacdcc3b72b656fed7ddb45845769419b04bfc1a514a92bc4"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.armv6l-linux-gnueabihf.tar.gz"
[[libssh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4f504eda9f33806e26ace52c3005d876f6cb22b2"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "171d9c3ba419adace212f0b8be34bcae64137bfb9284603e054ae9f82a6ac210"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.armv6l-linux-musleabihf.tar.gz"
[[libssh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40a3ef82cc0b798123dcd1fe81d061470727fd10"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "b3c9e47cb74ff6b6bd2f8579e6a91f94627916c6fee9087c2b49fa63eb04e351"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.armv7l-linux-gnueabihf.tar.gz"
[[libssh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b2d2902e7efb8457f500f21f99da069e69b37aa3"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "b5d5c3332e6b3fd3e8a13900c193b2e33653b87c0a0351bb3c401d8767f307ab"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.armv7l-linux-musleabihf.tar.gz"
[[libssh]]
arch = "i686"
git-tree-sha1 = "c31f0f87a5affb4508927e1a0742bd417cee7032"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "3a110e053395526ecd129148b57759ac38a4d8d03fb7a62c57e4d74e6d9c7f95"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.i686-linux-gnu.tar.gz"
[[libssh]]
arch = "i686"
git-tree-sha1 = "b1810972649128a74a751fd7e698f0fb6191baee"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "bb547b0cf09fa033b7670a2ba6421abd13d61a289801a50f7d434986bcf67a8e"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.i686-linux-musl.tar.gz"
[[libssh]]
arch = "i686"
git-tree-sha1 = "62416b787865f1c57200591cba4bdfc2484cec0e"
os = "windows"

    [[libssh.download]]
    sha256 = "8864db430b68dc67c8d6795c179c0b881e54685b377358579c8263d048c4cd3d"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.i686-w64-mingw32.tar.gz"
[[libssh]]
arch = "powerpc64le"
git-tree-sha1 = "ce8a66bbb39305c83f367348f22187141ebe75a4"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "a706a05d0bcabce461a3c2ffd867b14eeea3688e9a34fcbcc4aa8a33713e6196"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.powerpc64le-linux-gnu.tar.gz"
[[libssh]]
arch = "riscv64"
git-tree-sha1 = "444205e9872770093d22a785482aaef60ff1ba86"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "75c89346ab539ef275600a1cf7642544993f3be520782d06efc7ffa97bce0680"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.riscv64-linux-gnu.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "1d1b47b2f1afc511f3a84101e6e0f8496408adc1"
os = "macos"

    [[libssh.download]]
    sha256 = "af0dc136e58998edfdc6c8867ff22d6f28ed2d6f483dac5bc26fe2104cb34dc5"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.x86_64-apple-darwin.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "08ad7a4f8cbf0cefd9935dbe8ebe2ce8478c238c"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "5ec624dc34ff11e777b47e9e1fdb8bd10698ad3d5c9ce0cf4e045c910b873aa0"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.x86_64-linux-gnu.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "e7630d5edf8218b377e45fea926a5432e15c7ddf"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "de288327b6d71241e93874b6cbe7af864353d83ce24ab7aa19671f15b0b0ca6c"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.x86_64-linux-musl.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "f8fc218ed08d9276bb340505def9c4b4444c1bcf"
os = "freebsd"

    [[libssh.download]]
    sha256 = "a174b5ec070dfdf131db49c9356230ca285f027ada062e8ad306a889affcb345"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.x86_64-unknown-freebsd.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "e38f1b4650579b3351920dfdb58c43cef80e2216"
os = "windows"

    [[libssh.download]]
    sha256 = "091f736421505f51603a03f0b77aafdd4fe6dcc63afa2163bc481aad55442718"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.1+0/libssh.v0.12.1.x86_64-w64-mingw32.tar.gz"
