[[libssh]]
arch = "aarch64"
git-tree-sha1 = "e5d9a7af7ebcf1e4b932f241801514ce3fe55976"
os = "macos"

    [[libssh.download]]
    sha256 = "1b5da60f57a1cf9a5180575af5cce63f1d588049b74d0016da0b40fe03c9d587"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.aarch64-apple-darwin.tar.gz"
[[libssh]]
arch = "aarch64"
git-tree-sha1 = "518f947ecec3feb2bb219935736a71e1944e8215"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "9382095e23dd00619a819c9cc718085d0aae7b74a4533c825744c8bb25c6162e"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.aarch64-linux-gnu.tar.gz"
[[libssh]]
arch = "aarch64"
git-tree-sha1 = "0b380b131e73c91a29daec19c97a7bbf98258b96"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "a7f64aa566d7913bd403811e4a6ada68bdd802bd99969a02b187c6543321f6df"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.aarch64-linux-musl.tar.gz"
[[libssh]]
arch = "aarch64"
git-tree-sha1 = "77f08de8da44d381cb211cca604f0e09353b24eb"
os = "freebsd"

    [[libssh.download]]
    sha256 = "bcc1f1f63e1784f80b02418c3ff196ac0ccf0bcf700162d816da58e9b53eeeb9"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.aarch64-unknown-freebsd.tar.gz"
[[libssh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f60c8f5d4491a2c9b855b63807c2404ad9eb85e1"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "6d4f548cada2ac3c858eedafc76d0093fab45c536eb3b20dc4effd028c807f2c"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.armv6l-linux-gnueabihf.tar.gz"
[[libssh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f4915f5cf08202912d0a69057d01b83ceee51a5b"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "3889259735abc02953f2f6c030ef5c30fe40ce0cf045f507ad0c26ad006efbae"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.armv6l-linux-musleabihf.tar.gz"
[[libssh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8dad1ec5ed17707d56468088f8f3b8555b93485a"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "402caac088edd4d13da1ebd95373078ea0dca79ba15847170d93c695e89ec73c"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.armv7l-linux-gnueabihf.tar.gz"
[[libssh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9561f8aa59a63bb156575fb8701275b5a5033ba1"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "6c90e7c5a92339d934801afa70a1c4c4f36b73a980b84bc09f13b098b9a9f199"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.armv7l-linux-musleabihf.tar.gz"
[[libssh]]
arch = "i686"
git-tree-sha1 = "8f9d30984234bf8b9d86d6bfe7f3f6df85e81270"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "bbfe3c1aab4d2ad7639d9289f101a2e774fa2cb4815938706e55d70a04bf7241"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.i686-linux-gnu.tar.gz"
[[libssh]]
arch = "i686"
git-tree-sha1 = "89f0447a5dc4bdb0628f85275e810ce0cf7adfac"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "7e43daf29ccc9587eebb8f06d091361c997267dfea7e68c695ee9a096c82c8aa"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.i686-linux-musl.tar.gz"
[[libssh]]
arch = "i686"
git-tree-sha1 = "10eaaa2395427f77fd9a75a001c83a488825d353"
os = "windows"

    [[libssh.download]]
    sha256 = "3c8ffd9207025546a13817755a92ea876c5e6faae95d6b87b3c02d60a21d66cc"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.i686-w64-mingw32.tar.gz"
[[libssh]]
arch = "powerpc64le"
git-tree-sha1 = "0770f07653ed6a4b96f4e7b0e148691992d0322e"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "8b085a904c764b12c6ab47fcee96d5736bcd7c36fafabf8db451bec2b246dd1b"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.powerpc64le-linux-gnu.tar.gz"
[[libssh]]
arch = "riscv64"
git-tree-sha1 = "6c0dbf5e3e23fd73903503025dfe178a7632077b"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "b7a0978b23d3eef61243e1c111316b8ad04b7a00693dba78e9c56d9da78d1b03"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.riscv64-linux-gnu.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "03b7355860c74c40a2e93fd37bec0783448e200f"
os = "macos"

    [[libssh.download]]
    sha256 = "cc81dea498f9bf639b00354ce855beb2f6da1c173620da592c6080245e55a85c"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.x86_64-apple-darwin.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "d156a95a1775f34499a068430ecb1f075a62e3bd"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "97a6ab75d525aec8620de2465bb947b35996dc8b92bef830a414ab002766f9eb"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.x86_64-linux-gnu.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "4041a7f791629e3a3113796511efbe06a1ab7728"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "591d3a5f3b230fdf64360c73dde2091c309b1ceabd28e5bed84c9032ecd4030e"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.x86_64-linux-musl.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "d9413303b989cb9fbb40dd92d138ee63338fe7f4"
os = "freebsd"

    [[libssh.download]]
    sha256 = "3abd70dcd8cfeb656fa68bc8217b8ea36290260ac6644bffbb99c81d5d8158e0"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.x86_64-unknown-freebsd.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "8e1797af2e326d3c4c9576345f67928c9c4a7b23"
os = "windows"

    [[libssh.download]]
    sha256 = "5fe0d8b9d29ab7cb5949ec1b9e878c790588a66d63de0f1758ba76d153d75d0c"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.11.3+0/libssh.v0.11.3.x86_64-w64-mingw32.tar.gz"
