[[libssh]]
arch = "aarch64"
git-tree-sha1 = "0e6d16925a197c1a92a66cdf0c8a2dca3dd7933e"
os = "macos"

    [[libssh.download]]
    sha256 = "0e90ab1e0c593a8221ab872e57785f85b7e2366ca081db8de707f1c54538820a"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.aarch64-apple-darwin.tar.gz"
[[libssh]]
arch = "aarch64"
git-tree-sha1 = "80cb95622ddd3ed78216da4e0333131824ec4b6f"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "5b7be66b440ee2ac9989976dc700c3fb27017bc08291e4669a6f12e7a5650485"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.aarch64-linux-gnu.tar.gz"
[[libssh]]
arch = "aarch64"
git-tree-sha1 = "f60eff7e03e20103fffddff07d7617e2ae469e5a"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "5fa14efbf4538c25d2a20fde789d275c985769ecce4d8d54067cee66441b9408"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.aarch64-linux-musl.tar.gz"
[[libssh]]
arch = "aarch64"
git-tree-sha1 = "8296befb8457c53b4e19cbc2b556e37af16e30ec"
os = "freebsd"

    [[libssh.download]]
    sha256 = "fa0c9ed6f1534d45c9031d1a5b3636bcf7e33605607886afee3555a1d6f0e000"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.aarch64-unknown-freebsd.tar.gz"
[[libssh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "78c61647f920c18f4afe87d20ae3212f9f90be53"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "d4abf76b499daafa3982e5794d890b55f97535fa2ea28c56b77bb3360da3d290"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.armv6l-linux-gnueabihf.tar.gz"
[[libssh]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "764cc863ae9040e7fabae54dd72150c5d96d9169"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "d1bdbc18604b6b084ff77704991dfb090ce4883038e4a62c7c32e58733799ab0"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.armv6l-linux-musleabihf.tar.gz"
[[libssh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dc6378856ce2ffb3f76dd43558366fc97618b141"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "97cac571093e3dcd29304d6085b55e7052150bb778f43fb804e9963c40dac4af"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.armv7l-linux-gnueabihf.tar.gz"
[[libssh]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ddbd6c09a14318d97da7d9b2f4270dfbc3ca08da"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "55c6e7b44109f860cb2d1fe3243c495cb9393d75a1cae96bf55530b1bb550f00"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.armv7l-linux-musleabihf.tar.gz"
[[libssh]]
arch = "i686"
git-tree-sha1 = "3cd98dafa641e808608af73ce7dad4cd5e2fab30"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "58f592f33c20c817cb738e2a5159b6b7b0dfe84a07110745e99a505592b4057f"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.i686-linux-gnu.tar.gz"
[[libssh]]
arch = "i686"
git-tree-sha1 = "3ec4897d45629aed508124f7c63438ab3caf5254"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "dfa727db8e628ed509fcea7e2fd60933169d4282ab8de5b4fa23f7f9f3bce156"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.i686-linux-musl.tar.gz"
[[libssh]]
arch = "i686"
git-tree-sha1 = "409e58f8294fbcf4852a63362d10dbf9da9f7f7e"
os = "windows"

    [[libssh.download]]
    sha256 = "6c0585ab2661904c79601ccc6e57014f5d1802f251d9a59b3170fb419f0096ce"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.i686-w64-mingw32.tar.gz"
[[libssh]]
arch = "powerpc64le"
git-tree-sha1 = "0fc14846b81d7a31b731376fa33d28657e29d89b"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "672b46e619a3ea4b5df43d511686b2c0bf3ee2a5b5f5f61cf92853dace19ad8a"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.powerpc64le-linux-gnu.tar.gz"
[[libssh]]
arch = "riscv64"
git-tree-sha1 = "ac9d00a543b9042d9f5e82162a943cbcdaa9cfeb"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "68c499967e0478212bc4b1bd2aa984a4916851a6c8076c8ce7bfa5af7bf3475c"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.riscv64-linux-gnu.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "ec36c27a4f587cea7ce2c5969851ec9cfe5a188d"
os = "macos"

    [[libssh.download]]
    sha256 = "cc43340d88c8fde70c4a67647be99c2c044335941626173aa86d8c7d140a9c99"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.x86_64-apple-darwin.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "36ac4f79dcfbe87a3b24e51ccb4a6682157b39f3"
libc = "glibc"
os = "linux"

    [[libssh.download]]
    sha256 = "f6f846846a2f3df157c6746d6fddc04ccd7eb670fa0937632cfc85207ef48d91"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.x86_64-linux-gnu.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "3ffdc73beec1a76476f9498c01021bc4c26a5137"
libc = "musl"
os = "linux"

    [[libssh.download]]
    sha256 = "d6e66b66a252fe4cbab6bc2e334f5fb64fdf548a19f3b86ee6d760713b148d1b"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.x86_64-linux-musl.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "d1c1092f346a5116e79390817551d2717b989458"
os = "freebsd"

    [[libssh.download]]
    sha256 = "0afa9dd51491eea5ad11cdd6d631f6e3560f4723b62f66d543f7df02042dc194"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.x86_64-unknown-freebsd.tar.gz"
[[libssh]]
arch = "x86_64"
git-tree-sha1 = "2a9772e91568704126905251796e0e66697311e3"
os = "windows"

    [[libssh.download]]
    sha256 = "fb45f51c63f95f8313f5c28e836795ec09c1d53ee8630797af9c7b1e4db5c0f6"
    url = "https://github.com/JuliaBinaryWrappers/libssh_jll.jl/releases/download/libssh-v0.12.2+0/libssh.v0.12.2.x86_64-w64-mingw32.tar.gz"
