# Autogenerated wrapper script for libssh_jll for aarch64-apple-darwin
export doxygen_tags, libssh

using Kerberos_krb5_jll
using OpenSSL_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("libssh")
JLLWrappers.@declare_file_product(doxygen_tags)
JLLWrappers.@declare_library_product(libssh, "@rpath/libssh.4.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Kerberos_krb5_jll, OpenSSL_jll, Zlib_jll)
    JLLWrappers.@init_file_product(
        doxygen_tags,
        "usr/share/doc/libssh/tags.xml",
    )

    JLLWrappers.@init_library_product(
        libssh,
        "lib/libssh.4.10.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
